---
- name: add repository
  become: yes
  become_user: root
  template:
    dest: /etc/yum.repos.d/mongodb-org.repo
    src: files/repo.list

- name: install mongodb
  package:
    name: mongodb-org
    update_cache: yes
